#!env ruby
puts "Crystal REPL"
require "pry"
def crystal_eval(crystal)
  File.write("crystal_code.cr", "puts #{crystal}")
  require "open3"
  Open3.popen3("crystal crystal_code.cr") do |stdin, stdout, stderr, wait_thr|
    err = stderr.read
    raise stderr.read unless err.empty?
    return stdout.read
  end
end

def handle_input(input)
  result = crystal_eval(input)
  puts("=> #{result}")
end

loop do
  handle_input(Readline.readline(">> ", true))
end