#!env ruby
puts "Crystal REPL"
# require "pry"
require "readline"
PRINT_WARNINGS = false
def crystal_eval(crystal)
  File.write("crystal_code.cr", "puts #{crystal}")
  require "open3"
  Open3.popen3("crystal crystal_code.cr") do |stdin, stdout, stderr, wait_thr|
    begin
      err = stderr.read
      if !err.empty?
        if wait_thr.value.exitstatus == 0
          puts err if PRINT_WARNINGS
        else
          raise err
        end
      end
      return stdout.read
    end
  end
end

def handle_input(input)
  result = crystal_eval(input)
  puts("=> #{result}")
end

loop do
  handle_input(Readline.readline(">> ", true))
end